//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace AEOPoco.Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 文件状态
	/// </summary>
	public enum FileStatus : int
	{
		/// <summary>
		/// 否决
		/// </summary>
		Reject = -1,
		/// <summary>
		/// 上传
		/// </summary>
		Upload = 0,
		/// <summary>
		/// 申请审核
		/// </summary>
		ApplyAudit = 1,
		/// <summary>
		/// 审核
		/// </summary>
		Audit = 2,
		/// <summary>
		/// 作废
		/// </summary>
		Cancel = -2,
	}
}
