//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace AEOPoco.Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 操作记录类型
	/// </summary>
	public enum OperationNoteType : int
	{
		/// <summary>
		/// 文件要求
		/// </summary>
		FileUpload = 0,
		/// <summary>
		/// 项评分
		/// </summary>
		ItemScore = 1,
		/// <summary>
		/// 整改任务
		/// </summary>
		CorrectiveTask = 2,
	}
}
