//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace AEOPoco.Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum Role : int
	{
		/// <summary>
		/// 管理员
		/// </summary>
		Manager,
		/// <summary>
		/// 条负责人
		/// </summary>
		Clause,
		/// <summary>
		/// 评分人
		/// </summary>
		Score,
		/// <summary>
		/// 文件负责人
		/// </summary>
		Charge,
		/// <summary>
		/// 审核人
		/// </summary>
		Reviewer,
	}
}
