//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace AEOPoco.Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 评分级别
	/// </summary>
	public enum ScoreLevel : int
	{
		/// <summary>
		/// 不适用(不参与分值)
		/// </summary>
		NotApplicable = -3,
		/// <summary>
		/// 不达标(-2)
		/// </summary>
		Substandard = -2,
		/// <summary>
		/// 部分达标(-1)
		/// </summary>
		PartiallyCompliant = -1,
		/// <summary>
		/// 达标(0)
		/// </summary>
		ReachStandard = 0,
		/// <summary>
		/// 符合(2)
		/// </summary>
		Conform = 2,
		/// <summary>
		/// 不适用(0)
		/// </summary>
		NotApplicableV2 = 1,
	}
}
